---
title: "Week 13: STL set and map containers"
# draft: true
# draft-mode: visible
---

## SLOs for Week 13

At the end of this unit, students will be able to...

-   describe the unique characteristics of the STL set container -- e.g., that a set stores unique values in sorted order.
-   describe the time complexity of set container operations, like find, insert, remove.
-   write code using iterators to traverse all items in a set.
-   explain the behavior of an iterator.
-   describe the unique characteristics of the STL map container -- e.g., that a map stores key, value pairs, with unique keys stored in sorted order.
-   describe the time complexity of map container operations, like find, insert, remove, and indexing/subscripting.
-   reason about the unique behavior of indexing in a map object.
-   write code using iterators to traverse all items in a map. 

## Slides, videos, and application exercises

::::: slide-deck
**Week 13: Slides**

::: slides
[Slides](https://docs.google.com/presentation/d/1AtO1BnVb8WHNWg6ZYGCGav6y5zPqSPF8G5r-9VQbgLo/edit?usp=sharing){target="_blank"}
:::


::: reading
No readings for Week 13.

:::
:::::

<!-- ## Lab -->

::::: lab
**Lab 13: The STL set and map Containers**

::: instructions
[Instructions](/labs/lab13.qmd)
:::

::: starter
[Source](){target="_blank"}
:::

```{=html}
<!-- ::: slides
[Slides]()
::: -->
```
:::::

<!-- ## Homework assignments -->

::: homework
**Project 13: No Project**
:::

::: exam
**Exam 4** Exam on Wednesday during class. Bring your laptop. Content: Weeks 0 - 11.
:::