---
title: "Week 10: BSTs"
# draft: true
# draft-mode: visible
---

## SLOs for Week 10

At the end of this unit, students will be able to...

- articulate the operations one can do on a Binary Search Tree.
- understand the implementation of a BST and the algorithms for `insert`, `contains()`, `remove()`, `getHeight()`, the destructor, and the various traversals.
- reason about the complexity of operations on a BST -- for best and worst cases.
- describe the algorithm for finding the maximum node in a left subtree and minimum node in a right subtree, for use during the `remove()` algorithm.
- define what makes a BST **balanced**.
- AVL trees:
    - identify an AVL tree as a self-balancing tree.
    - articulate the importance of the balance factor in determining when the tree needs to be rebalanced.
    - compute the balance factor for a node.


## Slides, videos, and application exercises

::::: slide-deck
**Week 10: Slides**

::: slides
[Slides](https://docs.google.com/presentation/d/1-QiovhFtewcbIpT3x4bbeZXwb0aUgIa4Sj7Nt1ZC_as/edit?usp=sharing){target="_blank"}
:::

<!-- ::: source
[Code from Class](https://calvincollege-my.sharepoint.com/:f:/g/personal/vtn2_calvin_edu/Eredz2bHiShCtI0CVssiaggB8tUES6QbacEf2cc4PBhTgQ?e=uoV7Uu)
::: -->


::: reading
No readings for Week 10.

<!-- -   R4DS :: [Chp 2 - Introduction](https://r4ds.had.co.nz/explore-intro.html)
-   IMS :: [Sec 1.1 & 1.2 - Case study & Data basics](https://openintro-ims.netlify.app/data-hello.html) -->

:::

<!-- ::: video
[Video](https://youtu.be/_YqEHZccujc)
:::
-->

:::::

<!-- ## Lab -->

:::::: lab
**Lab 10: Binary Seach Trees**

::: instructions
[Instructions](/labs/lab10.qmd)
:::

<!-- ::: instructions
[Instructions](slides/lab06-slides.qmd)
::: -->


::: starter
[Source](https://classroom.github.com/a/m5CoIaV3)
:::

<!-- ::: slides
[Slides]()
::: -->
::::::

<!-- ## Homework assignments -->

::::: homework
**Project 10: Binary Search Trees**

::: instructions
[Instructions](/projects/proj10.qmd)
:::

<!-- ::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-10)
::: -->


::: starter
[Starter](https://classroom.github.com/a/f0Ju72P9){target={"_blank"}}
:::
:::::



<!-- ::: exam
**Exam 3**
Exam on Friday during class. Bring your laptop. Content: Weeks 0 - 8.
::: -->



<!-- ::: application-exercise
**First dataviz**

> **Option 1 - UN Votes**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01a-un-votes/unvotes.qmd)
> :::
>
> ::: video
> [Video](https://youtu.be/r-uTBEclM1E)
> :::

> **Option 2 - COVID-19**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/blob/master/course-materials/application-exercises/ae-01b-covid/covid.qmd)
> :::
::: -->



<!-- ::: guest-lecture
**Alberto Cairo - How charts lie**

::: video
[Video](https://youtu.be/Low28hx4wyk)
:::
::: -->
