---
title: "Week 4: Vectors -- dynamic arrays"
# draft: true
# draft-mode: visible
---

## SLOs for Week 4

Students will be able to...

- recognize a copy constructor and implement it.
- identify the 3 situations in which a copy constructor is called
- reason about the difference between a **shallow** and **deep** copy of a data structure.
- use the **new** operator to dynamically allocate memory and the **delete** and **delete[]** operators to free up the memory.
- explain when C++ calls the destructor on an object.
- explain when it is important to implement the destructor explicitly for a class.
- understand the implementation of a dynamic array data structure, including how it adapts its internal size to accommodate the number of values in the array.
- implement operator overloading for a class.

## Slides, videos, and application exercises

::: slide-deck
**Week 4: Slides**

::: slides
[Slides](https://docs.google.com/presentation/d/1drjTrJ0TrHNiqr7g0B_HxnN6MwswAR7SRWENpsPyLJw/edit?usp=sharing)
:::

<!-- ::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u5-d01-text-analysis)
::: -->

::: reading
No readings for Week 4.

<!-- -   R4DS :: [Chp 2 - Introduction](https://r4ds.had.co.nz/explore-intro.html)
-   IMS :: [Sec 1.1 & 1.2 - Case study & Data basics](https://openintro-ims.netlify.app/data-hello.html) -->
:::
<!-- ::: video
[Video](https://youtu.be/_YqEHZccujc)
:::
-->

:::

<!-- ## Lab -->

::: lab
**Lab 4: Vectors**

Vec -- A First Dynamic Data Structure

::: instructions
[Instructions](labs/lab-04/lab04.qmd)
:::

::: starter
[Source](https://classroom.github.com/a/VP5OQop2)
:::

::: slides
[Slides](./slides/lab04-slides.qmd)
:::
:::


<!-- ## Homework assignments -->

::: homework
**Project 4: Vec -- A First Dynamic Data Structure**

Vec -- A First Dynamic Data Structure

::: instructions
[Instructions](projects/proj-04/proj04.qmd)
:::

<!-- ::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-10)
::: -->

::: starter
[Starter](https://classroom.github.com/a/BR1S81yc)
:::
:::

<!-- ::: exam
**Exam 1**
Exam on Friday during class. Bring your laptop. Content: Weeks 0 - 2.
::: -->

<!-- ::: application-exercise
**First dataviz**

> **Option 1 - UN Votes**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01a-un-votes/unvotes.qmd)
> :::
>
> ::: video
> [Video](https://youtu.be/r-uTBEclM1E)
> :::

> **Option 2 - COVID-19**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/blob/master/course-materials/application-exercises/ae-01b-covid/covid.qmd)
> :::
::: -->


<!-- ::: guest-lecture
**Alberto Cairo - How charts lie**

::: video
[Video](https://youtu.be/Low28hx4wyk)
:::
::: -->