---
title: "Week 5: Generic Containers"
# draft: true
# draft-mode: visible
---

## SLOs for Week 5

By the end of this unit, students will be able to...

- describe when appending to a dynamic array is "inexpensive" and when it is "expensive".
- reason about the difference between a dynamic array's size and capacity.
- explain what a class template is to his or her grandma or grandpa.
- explain the reasons for creating class templates instead of classes.
- understand the Time Complexity terms linear time and constant time and amortized constant time.
- reason about the time complexity for operations on a dynamic array (append, insert, remove, copy constructor).

## Slides, videos, and application exercises

::: slide-deck
**Week 5: Slides**

::: slides
[Slides](https://docs.google.com/presentation/d/19Dyq-ocaGfhTA623PzKYofXuDHr-gz8eRP19zv65Mu0/edit?usp=sharing)
:::

::: source
[Code from Class](https://calvincollege-my.sharepoint.com/:f:/g/personal/vtn2_calvin_edu/Eredz2bHiShCtI0CVssiaggB8tUES6QbacEf2cc4PBhTgQ?e=uoV7Uu)
:::

::: reading
No readings for Week 5.

<!-- -   R4DS :: [Chp 2 - Introduction](https://r4ds.had.co.nz/explore-intro.html)
-   IMS :: [Sec 1.1 & 1.2 - Case study & Data basics](https://openintro-ims.netlify.app/data-hello.html) -->
:::
<!-- ::: video
[Video](https://youtu.be/_YqEHZccujc)
:::
-->

:::

<!-- ## Lab -->

::: lab
**Lab 5: Generic Containers (Templates)**

Generic Containers (Templates)

::: instructions
[Instructions](labs/lab-05/lab05.qmd)
:::

::: starter
[Source](https://classroom.github.com/a/_TFPzkme)
:::

::: slides
[Slides](./slides/lab05-slides.qmd)
:::
:::


<!-- ## Homework assignments -->

::: homework
**Project 4: Vec -- A First Dynamic Data Structure**

Vec -- A First Dynamic Data Structure

<!-- ::: instructions
[Instructions](projects/proj-04/proj04.qmd)
::: -->

<!-- ::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-10)
::: -->

::: starter
[Starter](https://classroom.github.com/a/BR1S81yc)
:::
:::

<!-- ::: exam
**Exam 1**
Exam on Friday during class. Bring your laptop. Content: Weeks 0 - 2.
::: -->

<!-- ::: application-exercise
**First dataviz**

> **Option 1 - UN Votes**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01a-un-votes/unvotes.qmd)
> :::
>
> ::: video
> [Video](https://youtu.be/r-uTBEclM1E)
> :::

> **Option 2 - COVID-19**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/blob/master/course-materials/application-exercises/ae-01b-covid/covid.qmd)
> :::
::: -->


<!-- ::: guest-lecture
**Alberto Cairo - How charts lie**

::: video
[Video](https://youtu.be/Low28hx4wyk)
:::
::: -->